services:
  - type: web
    name: golf-shot-backend
    env: node
    plan: free
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: golf-shot-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://golf-shot-backend.onrender.com/auth/google/callback
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://golf-shot-frontend.vercel.app
    region: oregon

databases:
  - name: golf-shot-db
    plan: starter 